dist: xenial
language: python

python: 3.7

if: (branch IN (master, beta, develop, ci-fixes)) OR (tag IS present)

env:
  global:
    - NOSEOPTS_DEFAULT="-v --with-timer --with-id --rednose"
    - NOSEOPTS_PARALLEL="--processes=-1 --process-timeout=2400" # timeout after 40 minutes (travis job timeout is 50 minutes)
    - NOSEOPTS_ALL="$NOSEOPTS_DEFAULT $NOSEOPTS_PARALLEL"
  matrix:
    - NOSETESTS="drivers objects" NOSEOPTS=$NOSEOPTS_ALL # first in build mx because long duration
    - NOSETESTS="algorithms" NOSEOPTS=$NOSEOPTS_ALL
    - NOSETESTS="algorithmsb" NOSEOPTS=$NOSEOPTS_ALL
    - NOSETESTS="tools iotest optimize construction extras" NOSEOPTS=$NOSEOPTS_ALL
    - NOSETESTS="report" NOSEOPTS=$NOSEOPTS_ALL
    - NOSETESTS="reportb" NOSEOPTS=$NOSEOPTS_ALL
    - NOSETESTS="mpi" NOSEOPTS=$NOSEOPTS_DEFAULT # cannot be run in parallel

# Install native package dependencies & initialize build environment
before_install:
  - >
    sudo apt-get update -qq -y &&
    sudo apt-get install -qq -y
    gfortran libblas-dev liblapack-dev openmpi-bin openmpi-common openssh-client
    openssh-server libopenmpi1.10 libopenmpi-dev libsuitesparse-dev
  - cmake --version
  - gcc --version

install:
  # Install base dependencies
  - pip install -e .
  # Install test dependencies
  - pip install -e .[testing]

# Default `test' stage script
script:
  - cd test/test_packages
  - nosetests $NOSEOPTS $NOSETESTS

# Cache pip packages
cache:
  pip: true
  timeout: 1000

stages:
  - name: lint
    if: NOT branch IN (master, beta)
  - name: lint-comprehensive
    if: branch IN (master, beta)
  - test
  # Run tests on python 2.7 & 3.5, but only on master/beta
  - name: test-extra
    if: branch IN (master, beta)
  - name: push
    if: (branch = develop) AND (NOT (type = pull_request))

jobs:
  include:
    - &lint-job
      stage: lint
      name: "PEP8"
      python: 3.7
      before_install: skip
      install:
        - pip install flake8
      script:
        - python -m flake8 --statistics $LINTOPTS packages/pygsti
    - <<: *lint-job
      name: "Critical errors"
      env: LINTOPTS="--config=.flake8-critical"
    - <<: *lint-job
      stage: lint-comprehensive
      name: "Comprehensive linting"

    # Can't use matrix expansion for included jobs or custom stages, so we'll manually list extra jobs
    - stage: test-extra
      python: 3.5
      env: NOSETESTS="drivers objects" NOSEOPTS=$NOSEOPTS_ALL
    - stage: test-extra
      python: 3.5
      env: NOSETESTS="algorithms" NOSEOPTS=$NOSEOPTS_ALL
    - stage: test-extra
      python: 3.5
      env: NOSETESTS="algorithmsb" NOSEOPTS=$NOSEOPTS_ALL
    - stage: test-extra
      python: 3.5
      env: NOSETESTS="tools iotest optimize construction extras" NOSEOPTS=$NOSEOPTS_ALL
    - stage: test-extra
      python: 3.5
      env: NOSETESTS="report" NOSEOPTS=$NOSEOPTS_ALL
    - stage: test-extra
      python: 3.5
      env: NOSETESTS="reportb" NOSEOPTS=$NOSEOPTS_ALL
    - stage: test-extra
      python: 3.5
      env: NOSETESTS="mpi" NOSEOPTS=$NOSEOPTS_ALL

    - stage: test-extra
      python: 2.7
      env: NOSETESTS="drivers objects" NOSEOPTS=$NOSEOPTS_ALL
    - stage: test-extra
      python: 2.7
      env: NOSETESTS="algorithms" NOSEOPTS=$NOSEOPTS_ALL
    - stage: test-extra
      python: 2.7
      env: NOSETESTS="algorithmsb" NOSEOPTS=$NOSEOPTS_ALL
    - stage: test-extra
      python: 2.7
      env: NOSETESTS="tools iotest optimize construction extras" NOSEOPTS=$NOSEOPTS_ALL
    - stage: test-extra
      python: 2.7
      env: NOSETESTS="report" NOSEOPTS=$NOSEOPTS_ALL
    - stage: test-extra
      python: 2.7
      env: NOSETESTS="reportb" NOSEOPTS=$NOSEOPTS_ALL
    - stage: test-extra
      python: 2.7
      env: NOSETESTS="mpi" NOSEOPTS=$NOSEOPTS_ALL

    - stage: push
      env: PUSH_BRANCH="beta"
      install: skip
      before_install:
        - >-
          openssl aes-256-cbc
          -K $encrypted_8f2a7a9a4246_key
          -iv $encrypted_8f2a7a9a4246_iv
          -in CI/github_deploy_key.enc
          -out CI/github_deploy_key
          -d
        - chmod 600 CI/github_deploy_key
        - eval $(ssh-agent -s)
        - ssh-add CI/github_deploy_key
      script:
        - CI/push.sh

  allow_failures:
    - stage: lint
      name: "PEP8"

deploy:
  provider: pypi
  user: pygsti-ci
  password:
    secure: vK9Lm939ZRMgQ/UdpCRSrbiWSN5h0e0/vKV+ZCtUL63KHMaK9AShSJhNOWZ2RUIi3c/ZKTlllCgj9O/r0MjP2qE5N3DLhm0t+QNjgMM4Iz4bsMJx4nPYTrAeiShyffPFJWSVSP9l6054mBGZow6aeZEzDGsF2Y3LzISzE47c8xFxJI2TSM1AJ+j1feRsayTDepBq5+di2z3GgBXT8qDWMS4EY+ljdgsHBQ5xRh3HmT5AcecltwRmNaWprLSukjpmTuX+HKgMazSKCsqvTXSuhKive+7OxONu0JGva14GGk9baO3mGVaYA0+9R72QIQxD2hKdLwzHzYeo1Rue1AAggKdlSUDZ5InrqXx2ASkdqyqw7p6GUyxEQGErSvbqyPqgyCs0wNkxZR9xAGeUX9SztZxhgQyFlZRdq0gahSQB6vuwlbg8NlV/hMW94n/wk+NrARf7fCSw9rglIaTECGjcxaijc4r+EAVwyiEwtoT7wsei1A2sNfxHBJaZfjy7VXPhE5oSswPQV4B5uS9pxuiEWFfFor4e+iHtwQTR/KkKDrm0OOmWSemHgO4MLubupPrTzyViGfHM7BGHNe8D9FpY+IgMV/7Je+WwbDfccY4PZgjKZq1HYHnbQIhIyO7nckU6LXh1YPC/32NxOCThB+0H484B5dvPYjprIXQ+xIDRcKc=
  distributions: "sdist bdist_wheel"
  skip_existing: true
  on:
    tags: true

notifications:
  email:
    on_success: change
    on_failure: always
