# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: PyGSTi Documentation
author: PyGSTi Developers
logo: pyGSTi_icon_wht.png

# Cache executed notebooks between builds.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: 'off'

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: pygsti-docs.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/sandialabs/pyGSTi  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: feature-jupyterbook  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  home_page_in_navbar: false

# Which notebook interface to open
# Note, must be classic to automatically convert MD to the ipynb
# And then we point to public BinderHub
launch_buttons:
  notebook_interface: "classic" # or "jupyterlab"
  binderhub_url: "https://mybinder.org"

# Sphinx options
sphinx:
  extra_extensions:
  - 'sphinx.ext.napoleon'
  - 'sphinx.ext.autodoc'
  - 'sphinx.ext.autosummary'
  - 'sphinx.ext.viewcode'
  - 'sphinx.ext.doctest'
  - 'sphinx.ext.intersphinx'
  - 'sphinx.ext.mathjax'
  config:
    add_module_names: False
    autosummary_generate: True
    autoclass_content: "both"
    autodoc_typehints: "description"
    autodoc_member_order: "groupwise"
    exclude_patterns: ["notebooks/", "**/*.ipynb"]
    suppress_warnings:
    - "etoc.toctree"
    templates_path: ["_templates"]
